apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customController
  name: customController
  namespace: customController
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customController
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customController
    spec:
      containers:
      - image: pavangujar23/customController:0.1.0
        name: customController
        resources: {}
      serviceAccountName: customController-sa
status: {}